version: 0.2
env:
  variables:
    BROWSER: "chrome"
phases:
  install:
    commands:
      - wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      - mv chromedriver /usr/bin/chromedriver
      - chromedriver --version
      - npm i -g cucumber
      - npm i -g selenium-webdriver
  pre_build:
    commands:
      - npm install
      - pip install --upgrade awscli
  build:
    commands:
      - npm run test


artifacts:
  files: '**/*'