version: 0.2

phases:
  install:
    commands:
      - npm i -g cucumber
      - npm i -g selenium-webdriver
  pre_build:
    commands:
      - npm install
      - pip install --upgrade awscli
  build:
    commands:
      - npm run test


artifacts:
  files: '**/*'