version: 0.2

phases:
  install:
    commands:
      - npm i -g cucumber
      - npm i -g selenium-webdriver
      - npm i -g chromedriver
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run test